owner: currenjin
repo: upptime

sites:
  - name: Currenjin's Wiki
    url: https://currenjin.github.io
  - name: Currenjin's Blog
    url: https://simpleisit.tistory.com

status-website:
  baseUrl: upptime
  name: currenjin
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
