owner: currenjin
repo: upptime

sites:
  - name: Currenjin's Wiki
    url: https://currenjin.github.io
  - name: simpleisIt
    url: https://simpleisit.tistory.com

status-website:
  baseUrl: upptime
  name: currenjin
